### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by joonjeong** [hufscse-linux/PoEAA#7]
최근 업데이트 코드에 덧붙여, 아래 패턴 학습해볼 것.
http://martinfowler.com/eaaCatalog/queryObject.html

StudentMapperTest 코드를 바탕으로 아래 리펙토링 및 추가 작업 해볼 것.
1. Lambda 기반으로 작성된 테스트 코드에서 Lambda 코드를 기능 클래스로 분리하여 리팩토링해볼 것.
2. Refactoring한 Class, Sequence Diagram 그리기. 시작점은 테스트 프로그램에서.
3. Strategy, Template Method, Mapper를 바탕으로 Facade 형태로 구현할 수 있는 방법을 고민해볼 것.
4. Connection과 Session의 차이를 생각해볼 것.
5. Java Reflection을 기반으로 Mapper의 기능 일부를 자동화시킬 수 있는지 생각해볼 것.

위 코드들을 파이썬으로 작성해보고 싶으면 파이썬으로 구현해도 상관없음.

**Comment by SunKyu** [comment]
기능 클래스가 무엇을 의미하는지 잘 모르겠습니다.
단순하게 세션기능을 클래스로 분리하는 것을 얘기하시는건가요??? 
또한 기능클래스로 분리를 테스트 코드가 아닌 실제 코드에 적용을 해야하는 걸 의미하신건가요?
