### ISSUE TITLE
Assignment

### ISSUE THREAD

**Issue by joonjeong** [hufscse-linux/PoEAA#9]
# Assignments
1. #7 review 후 test 디렉토리에서 main 디렉토리로 분리하여 PR
2. 7dc74e3 를 참고하여 아래 주제들에 대해 생각해볼 것.
   - JDBC, Spring JDBC, MyBatis, Hibernate에서 SQL 데이터를 어떻게 비교하는가?
   - Java8 이전의 익명 클래스 기반 클로저와 람다 기반의 클로저 코드는 어떻게 차이가 있는가?
   - MyBatis, Hibernate에서의 SessionFactory, Session, Criteria/Query API 형태로 디자인함으로서 얻을 수 있는 이점은 무엇인가?
3. MyBatis, Hibernate에서는 매핑을 위하여 Java Reflection API를 사용한다. Mapper 구현 시에 이를 활용하려면 어떻게 해야하는지 Reflection API를 리뷰하고, [Metadata Mapping](http://martinfowler.com/eaaCatalog/metadataMapping.html) 패턴을 공부해 올 것.
4. [Query Object](http://martinfowler.com/eaaCatalog/queryObject.html) 패턴이 적용되었는데, 이 API는 현재 완전체라 볼 수 없는 상태. 이것을 Hibernate, JPA에서는 어떻게 구현하고 있는지 살펴볼 것. JPA는 버전 2.x 미만을 참고하는 것이 좋을것임.
5. [Catalog of Patterns of Enterprise Application Architecture](http://martinfowler.com/eaaCatalog/)에서 현재까지 학습한 패턴들의 이름을 정리해올 것.

**Comment by SunKyu** [comment]
## 2
- JDBC  
- 익명 클래스기반 클로저보다 람다기반의 클로저 코드는 좀 더 간결하게 작성가능.
- 로직 부분에서는 실제 맵핑하는 코드만 작성, 나머지부분(자원회수, 커넥션 관리, 쿼리 작성)은 따로 신경을 안써도 됨.(라이브러리 단에서 처리해주기 때문). 

---

## 3
- 메타데이터를 이용하여 필요한 정보 획득, 클래스 알아내고 메소드 알아내고 파라미터 알아내고 사용

---

## 4

Hibernate 에서는 HQL 사용, HQL(SQL과 비슷)은 query 오브젝트로써 여러 메소드들이 인터페이스에 정의되어있다. 
Table과 컬럼기반으로 하지 않고 매핑될 특정 객체와 필드를 가지고 동작

## 

## 5.
1. Mapper
2. Metadata Mapping
3. Query Object
